pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    bat 'mvnw.cmd clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    bat 'mvnw.cmd test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('backend') {
                    bat 'mvnw.cmd package'
                }
            }
        }
    }
}